# 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Display more columns
pd.set_option('display.max_columns', None)

# 2. Load datasets

In [2]:
deaths = pd.read_csv("CovidDeaths.csv")
vaccinations = pd.read_csv("CovidVaccinations.csv")

SELECT *
FROM coviddeaths;

In [3]:
deaths.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,24/02/2020,1.0,1.0,NaN,NaN,NaN,NaN,0.026,0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,25/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,26/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,27/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,28/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

SELECT location, date, total_cases, new_cases, total_deaths, population
FROM coviddeaths
ORDER BY location, date;

In [4]:
df = deaths[[
    "location",
    "date",
    "total_cases",
    "new_cases",
    "total_deaths",
    "population"
]]

df = df.sort_values(["location","date"])

df.head()

        location        date  total_cases  new_cases  total_deaths  population
312  Afghanistan  01/01/2021      51526.0        0.0        2191.0  38928341.0
343  Afghanistan  01/02/2021      55059.0       36.0        2404.0  38928341.0
6    Afghanistan  01/03/2020          1.0        0.0           NaN  38928341.0
371  Afghanistan  01/03/2021      55733.0       19.0        2444.0  38928341.0
37   Afghanistan  01/04/2020        197.0       22.0           4.0  38928341.0

SELECT *
FROM coviddeaths
WHERE continent IS NOT NULL
ORDER BY location, date;

In [5]:
df = deaths[deaths["continent"].notna()]

df = df.sort_values(["location","date"])

df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
312,AFG,Asia,Afghanistan,01/01/2021,51526.0,0.0,102.286,2191.0,0.0,7.429,1323.612,0.000,2.628,56.283,0.000,0.191,0.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.04,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
343,AFG,Asia,Afghanistan,01/02/2021,55059.0,36.0,55.286,2404.0,4.0,2.714,1414.368,0.925,1.420,61.754,0.103,0.070,0.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.04,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
6,AFG,Asia,Afghanistan,01/03/2020,1.0,0.0,0.143,NaN,NaN,0.000,0.026,0.000,0.004,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.78,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
371,AFG,Asia,Afghanistan,01/03/2021,55733.0,19.0,16.571,2444.0,1.0,1.571,1431.682,0.488,0.426,62.782,0.026,0.040,0.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1580.0,NaN,NaN,NaN,41.0,12.04,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
37,AFG,Asia,Afghanistan,01/04/2020,197.0,22.0,17.286,4.0,0.0,0.286,5.061,0.565,0.444,0.103,0.000,0.007,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.59,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

### Likelihood of Dying if Infected

SELECT location, date, total_cases, total_deaths,
(total_deaths/total_cases)*100 AS death_percentage
FROM coviddeaths
WHERE location = 'Algeria'
ORDER BY location, date;

In [6]:
df = deaths[deaths["location"] == "Algeria"].copy()

df["death_percentage"] = (
    df["total_deaths"] / df["total_cases"]
) * 100

df = df.sort_values(["location","date"])

df[["location","date","total_cases","total_deaths","death_percentage"]].head()

     location        date  total_cases  total_deaths  death_percentage
1617  Algeria  01/01/2021      99897.0        2762.0          2.764848
1648  Algeria  01/02/2021     107578.0        2894.0          2.690141
1311  Algeria  01/03/2020          1.0           NaN               NaN
1676  Algeria  01/03/2021     113255.0        2987.0          2.637411
1342  Algeria  01/04/2020        847.0          58.0          6.847698

### Percentage of Population Infected

SELECT location, date, population, total_cases,
(total_cases/population)*100 AS covid_percentage
FROM coviddeaths
ORDER BY location, date;

In [7]:
df["covid_percentage"] = (
    deaths["total_cases"] /
    deaths["population"]
) * 100

df = df[
    ["location","date","population","total_cases","covid_percentage"]
].sort_values(["location","date"])

df.head()

     location        date  population  total_cases  covid_percentage
1617  Algeria  01/01/2021  43851043.0      99897.0          0.227810
1648  Algeria  01/02/2021  43851043.0     107578.0          0.245326
1311  Algeria  01/03/2020  43851043.0          1.0          0.000002
1676  Algeria  01/03/2021  43851043.0     113255.0          0.258272
1342  Algeria  01/04/2020  43851043.0        847.0          0.001932

### Countries with Highest Infection Rate

SELECT location, population,
MAX(total_cases) AS HighestInfectionCount,
MAX(total_cases/population)*100 AS percent_of_population_infected
FROM coviddeaths
GROUP BY location, population
ORDER BY percent_of_population_infected DESC;

In [8]:
df = (
    deaths.groupby(["location","population"], as_index=False)
    .agg(
        HighestInfectionCount=("total_cases","max")
    )
)

df["percent_of_population_infected"] = (
    df["HighestInfectionCount"] /
    df["population"]
) * 100

df.sort_values(
    "percent_of_population_infected",
    ascending=False
).head(10)

,location,population,HighestInfectionCount,percent_of_population_infected
4,Andorra,77265.0,13232.0,17.125477
132,Montenegro,628062.0,97389.0,15.506272
51,Czechia,10708982.0,1630758.0,15.227946
168,San Marino,33938.0,5066.0,14.927220
177,Slovenia,2078932.0,240292.0,11.558435
116,Luxembourg,625976.0,67205.0,10.736035
16,Bahrain,1701583.0,176934.0,10.398200
172,Serbia,6804596.0,689557.0,10.133695
206,United States,331002647.0,32346971.0,9.772421
97,Israel,8655541.0,838481.0,9.687217

### Countries with Highest Death Count

SELECT location, MAX(total_deaths) AS total_death_count
FROM coviddeaths
GROUP BY location
ORDER BY total_death_count DESC;

In [9]:
df["total_deaths"] = pd.to_numeric(
    deaths["total_deaths"], errors="coerce"
)

df = (
    deaths.groupby("location", as_index=False)
    .agg(total_death_count=("total_deaths","max"))
)

df.sort_values("total_death_count", ascending=False).head(10)

           location  total_death_count
215           World          3180238.0
65           Europe          1016750.0
146   North America           847942.0
66   European Union           688896.0
183   South America           672415.0
208   United States           576232.0
11             Asia           520286.0
28           Brazil           403781.0
128          Mexico           216907.0
91            India           211853.0

### Death Count by Continent

SELECT continent, MAX(total_deaths) AS total_death_count
FROM coviddeaths
WHERE continent IS NOT NULL
GROUP BY continent
ORDER BY total_death_count DESC;

In [10]:
df = deaths[
    deaths["continent"].notna()
]

df = (
    df.groupby("continent", as_index=False)
    .agg(total_death_count=("total_deaths","max"))
)

df.sort_values(
    "total_death_count",
    ascending=False
)

       continent  total_death_count
3  North America           576232.0
5  South America           403781.0
1           Asia           211853.0
2         Europe           127775.0
0         Africa            54350.0
4        Oceania              910.0

### Global Numbers

SELECT SUM(new_cases),
SUM(new_deaths),
SUM(new_deaths)/SUM(new_cases)*100 AS death_percentage
FROM coviddeaths
WHERE continent IS NOT NULL;

In [11]:
deaths["new_deaths"] = pd.to_numeric(
    deaths["new_deaths"], errors="coerce"
)

global_data = deaths[deaths["continent"].notna()]

total_cases = global_data["new_cases"].sum()
total_deaths = global_data["new_deaths"].sum()

death_percentage = (total_deaths / total_cases) * 100

print("Total Cases:", total_cases)
print("Total Deaths:", total_deaths)
print("Death Percentage:", death_percentage)

Total Cases: 150574977.0
Total Deaths: 3180206.0
Death Percentage: 2.1120414981036326

### Vaccination Table

SELECT * FROM covidvaccinations;

In [12]:
vaccinations.head()

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,24/02/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,25/02/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,26/02/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,27/02/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,28/02/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

### Population vs Vaccinations (JOIN)

SELECT dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations
FROM coviddeaths AS dea
JOIN covidvaccinations AS vac
ON dea.location = vac.location
AND dea.date = vac.date;

In [13]:
merged = pd.merge(
    deaths,
    vaccinations,
    on=["location","date"],
    how="inner"
)

merged.head()

,iso_code_x,continent_x,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests_x,total_tests_x,total_tests_per_thousand_x,new_tests_per_thousand_x,new_tests_smoothed_x,new_tests_smoothed_per_thousand_x,positive_rate_x,tests_per_case_x,tests_units_x,total_vaccinations_x,people_vaccinated_x,people_fully_vaccinated_x,new_vaccinations_x,new_vaccinations_smoothed_x,total_vaccinations_per_hundred_x,people_vaccinated_per_hundred_x,people_fully_vaccinated_per_hundred_x,new_vaccinations_smoothed_per_million_x,stringency_index_x,population,population_density_x,median_age_x,aged_65_older_x,aged_70_older_x,gdp_per_capita_x,extreme_poverty_x,cardiovasc_death_rate_x,diabetes_prevalence_x,female_smokers_x,male_smokers_x,handwashing_facilities_x,hospital_beds_per_thousand_x,life_expectancy_x,human_development_index_x,iso_code_y,continent_y,new_tests_y,total_tests_y,total_tests_per_thousand_y,new_tests_per_thousand_y,new_tests_smoothed_y,new_tests_smoothed_per_thousand_y,positive_rate_y,tests_per_case_y,tests_units_y,total_vaccinations_y,people_vaccinated_y,people_fully_vaccinated_y,new_vaccinations_y,new_vaccinations_smoothed_y,total_vaccinations_per_hundred_y,people_vaccinated_per_hundred_y,people_fully_vaccinated_per_hundred_y,new_vaccinations_smoothed_per_million_y,stringency_index_y,population_density_y,median_age_y,aged_65_older_y,aged_70_older_y,gdp_per_capita_y,extreme_poverty_y,cardiovasc_death_rate_y,diabetes_prevalence_y,female_smokers_y,male_smokers_y,handwashing_facilities_y,hospital_beds_per_thousand_y,life_expectancy_y,human_development_index_y
0,AFG,Asia,Afghanistan,24/02/2020,1.0,1.0,NaN,NaN,NaN,NaN,0.026,0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,AFG,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,25/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,AFG,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,26/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,AFG,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,27/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,AFG,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,28/02/2020,1.0,0.0,NaN,NaN,NaN,NaN,0.026,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,38928341.0,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,AFG,Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.33,54.422,18.6,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

### Rolling People Vaccinated (Window Function)

SUM(vac.new_vaccinations)
OVER (PARTITION BY dea.location ORDER BY dea.date)

In [14]:
merged["new_vaccinations"] = pd.to_numeric(
    vaccinations["new_vaccinations"], errors="coerce"
)

merged = merged.sort_values(["location","date"])

merged["RollingPeopleVaccinated"] = (
    merged.groupby("location")["new_vaccinations"]
    .cumsum()
)

### Percentage of Population Vaccinated (CTE Equivalent)

WITH PopVsVac AS (...)
SELECT *,
(RollingPeopleVaccinated/Population)*100
FROM PopVsVac;

In [15]:
merged["percent_population_vaccinated"] = (
    merged["RollingPeopleVaccinated"] /
    merged["population"]
) * 100

merged[
    ["location","date","population",
     "RollingPeopleVaccinated",
     "percent_population_vaccinated"]
].head()

,location,date,population,RollingPeopleVaccinated,percent_population_vaccinated
312,Afghanistan,01/01/2021,38928341.0,NaN,NaN
343,Afghanistan,01/02/2021,38928341.0,NaN,NaN
6,Afghanistan,01/03/2020,38928341.0,NaN,NaN
371,Afghanistan,01/03/2021,38928341.0,NaN,NaN
37,Afghanistan,01/04/2020,38928341.0,NaN,NaN

### Temporary Table Equivalent

CREATE TEMPORARY TABLE percent_population_vaccinated

In [16]:
percent_population_vaccinated = pd.merge(
    deaths[["continent","location","date","population"]],
    merged[["location","date","new_vaccinations","RollingPeopleVaccinated"]],
    on=["location","date"]
)

percent_population_vaccinated.head()

,continent,location,date,population,new_vaccinations,RollingPeopleVaccinated
0,Asia,Afghanistan,24/02/2020,38928341.0,NaN,NaN
1,Asia,Afghanistan,25/02/2020,38928341.0,NaN,NaN
2,Asia,Afghanistan,26/02/2020,38928341.0,NaN,NaN
3,Asia,Afghanistan,27/02/2020,38928341.0,NaN,NaN
4,Asia,Afghanistan,28/02/2020,38928341.0,NaN,NaN

### View Equivalent

CREATE VIEW PercentPopulationVaccinated AS
SELECT ...

In [17]:
PercentPopulationVaccinated = percent_population_vaccinated.copy()

PercentPopulationVaccinated.head()

,continent,location,date,population,new_vaccinations,RollingPeopleVaccinated
0,Asia,Afghanistan,24/02/2020,38928341.0,NaN,NaN
1,Asia,Afghanistan,25/02/2020,38928341.0,NaN,NaN
2,Asia,Afghanistan,26/02/2020,38928341.0,NaN,NaN
3,Asia,Afghanistan,27/02/2020,38928341.0,NaN,NaN
4,Asia,Afghanistan,28/02/2020,38928341.0,NaN,NaN

## SQL vs Pandas Concepts

| SQL             | Pandas                 |
| --------------- | ---------------------- |
| SELECT          | Column selection       |
| WHERE           | Boolean filtering      |
| ORDER BY        | `sort_values()`        |
| GROUP BY        | `groupby()`            |
| JOIN            | `merge()`              |
| SUM()           | `.sum()`               |
| MAX()           | `.max()`               |
| Window Function | `groupby().cumsum()`   |
| CTE             | Intermediate DataFrame |
| Temp Table      | New DataFrame          |
| View            | Saved DataFrame        |